# -*- coding: utf-8 -*-
"""topsis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/166-wdXXpy-_lwMYIMZ_KKyE4P_mYMeL_

TOPSIS for Text Summarization of Pre Trained Models
"""

import numpy as np
import pandas as pd

data=pd.read_csv("/data.csv")
data.head()

Rouge_scores=data['Rouge_Scores'].values
BLEU_scores=data['BLEU_Scores'].values
F1_scores=data['F1_Scores'].values

weights=np.array([0.5,0.25,0.25])

norm_matrix=np.column_stack([Rouge_scores,BLEU_scores,F1_scores])
norm_matrix

weighted_matrix=norm_matrix*weights

ideal_solution=np.max(weighted_matrix,axis=0)
negative_ideal_solution=np.min(weighted_matrix,axis=0)

distance_to_ideal = np.sqrt(np.sum((weighted_matrix - ideal_solution)**2, axis=1))
distance_to_negative_ideal = np.sqrt(np.sum((weighted_matrix - negative_ideal_solution)**2, axis=1))

topsis_scores = distance_to_negative_ideal / (distance_to_ideal + distance_to_negative_ideal)

data['TOPSIS_Score'] = topsis_scores
data['Rank'] = data['TOPSIS_Score'].rank(ascending=False)

print("Model Rank:")
print(data[['Model', 'TOPSIS_Score', 'Rank']].sort_values(by='Rank'))

data.to_csv('result.csv',index=False)